[package]
name = "eshkol-backend"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
eshkol-core = { path = "../eshkol-core" }
eshkol-frontend = { path = "../eshkol-frontend" }
eshkol-runtime = { path = "../eshkol-runtime" }

[lib]
path = "src/lib.rs"
